[package]
name = "utility"
version = "0.1.0"
authors = ["yangzhang214024 <yangzhang214024@sohu-inc.com>"]

[dependencies]
zookeeper = "0.5"
log = "0.4"
uuid = { version = "0.2", features = ["serde", "v4"] }
crossbeam = "0.7"